apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cadgenesis.fullname" . }}-config
  labels:
    {{- include "cadgenesis.labels" . | nindent 4 }}
data:
  platform.json: |
    {{- .Values.config.platformJson | nindent 4 }}
