{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cadgenesis.fullname" . }}-models
  labels:
    {{- include "cadgenesis.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadOnlyMany"]
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
