"""cadsecure - Secure execution layer for CADGenesis-LM.

Provides sandboxing, permission validation, and resource management
for CAD operations generated by the LLM.

Usage:
    from cadsecure import sandbox_execute, sandbox_create_config, sandbox_status, sandbox_test
    
    # Create config
    config = sandbox_create_config(30.0, 1024)
    
    # Execute operation
    result = sandbox_execute("cad.create_box", {"length": 10.0, "width": 5.0, "height": 3.0}, config)
    
    # Check status
    status = sandbox_status(config)
"""

from __future__ import annotations

import math

# ============================================================
# Sandbox Configuration
# ============================================================

class SandboxConfig:
    """Configuration for CAD operation sandbox execution."""
    
    def __init__(
        self,
        max_execution_time: float = 30.0,
        max_memory_mb: int = 1024,
        allowed_operations: list | None = None,
        disallowed_operations: list | None = None,
        max_result_size_mb: int = 100,
    ):
        self.max_execution_time = max_execution_time
        self.max_memory_mb = max_memory_mb
        self.allowed_operations = allowed_operations if allowed_operations is not None else []
        self.disallowed_operations = disallowed_operations if disallowed_operations is not None else []
        self.max_result_size_mb = max_result_size_mb
    
    def is_operation_allowed(self, operation: str) -> bool:
        """Check if an operation is allowed by the sandbox policy."""
        if not self.allowed_operations:
            if self.disallowed_operations:
                return operation not in self.disallowed_operations
            return True
        return operation in self.allowed_operations


# ============================================================
# Sandbox Result
# ============================================================

class SandboxResult:
    """Result of a sandboxed CAD operation execution."""
    
    def __init__(
        self,
        success: bool,
        message: str,
        execution_time: float,
        memory_used_mb: float,
        output: str = "",
    ):
        self.success = success
        self.message = message
        self.execution_time = execution_time
        self.memory_used_mb = memory_used_mb
        self.output = output
    
    def __repr__(self) -> str:
        return (
            f"SandboxResult(success={self.success}, "
            f"time={self.execution_time:.2f}s, "
            f"memory={self.memory_used_mb:.2f}MB)"
        )


# ============================================================
# Public API Functions
# ============================================================

def sandbox_execute(
    operation: str,
    parameters: dict,
    max_execution_time: float = 30.0,
    max_memory_mb: int = 1024,
) -> dict:
    """Execute a CAD operation in a secure sandbox.
    
    Args:
        operation: CAD operation name (e.g., "cad.create_box")
        parameters: Operation parameters dictionary
        max_execution_time: Maximum time in seconds
        max_memory_mb: Maximum memory in MB
    
    Returns:
        Dictionary with execution results
    """
    # Create config
    config = SandboxConfig(
        max_execution_time=max_execution_time,
        max_memory_mb=max_memory_mb,
        allowed_operations=parameters.get("allowed_operations"),
        disallowed_operations=parameters.get("disallowed_operations"),
        max_result_size_mb=parameters.get("max_result_size_mb", 100),
    )
    
    # Check if operation is allowed
    if not config.is_operation_allowed(operation):
        return {
            "success": False,
            "message": f"Operation '{operation}' not allowed by sandbox policy",
            "execution_time": 0.0,
            "memory_used_mb": 0.0,
            "output": "",
        }
    
    # Check for disallowed patterns (OS access, etc.)
    disallowed_patterns = ["os::", "std::fs::", "::system::", "spawn", "exec"]
    operation_lower = operation.lower()
    for pattern in disallowed_patterns:
        if pattern in operation_lower:
            return {
                "success": False,
                "message": f"Operation '{operation}' contains disallowed pattern '{pattern}'",
                "execution_time": 0.0,
                "memory_used_mb": 0.0,
                "output": "",
            }
    
    # Execute based on operation type
    if operation == "cad.create_box":
        length = parameters.get("length", 10.0)
        width = parameters.get("width", 5.0)
        height = parameters.get("height", 3.0)
        
        if length <= 0 or width <= 0 or height <= 0:
            return {
                "success": False,
                "message": "Box dimensions must be positive",
                "execution_time": 0.0,
                "memory_used_mb": 0.0,
                "output": "",
            }
        
        message = f"Box created: {length}x{width}x{height} units"
        output = f"Box({length}, {width}, {height})"
        
        return {
            "success": True,
            "message": message,
            "execution_time": 0.1,
            "memory_used_mb": 1.0,
            "output": output,
        }
    
    elif operation == "cad.create_sphere":
        radius = parameters.get("radius", 5.0)
        
        if radius <= 0:
            return {
                "success": False,
                "message": "Sphere radius must be positive",
                "execution_time": 0.0,
                "memory_used_mb": 0.0,
                "output": "",
            }
        
        message = f"Sphere created: radius={radius} units"
        output = f"Sphere(radius={radius})"
        
        return {
            "success": True,
            "message": message,
            "execution_time": 0.1,
            "memory_used_mb": 0.5,
            "output": output,
        }
    
    elif operation == "cad.calculate_distance":
        p1 = (
            parameters.get("p1_x", 0.0),
            parameters.get("p1_y", 0.0),
            parameters.get("p1_z", 0.0),
        )
        p2 = (
            parameters.get("p2_x", 1.0),
            parameters.get("p2_y", 1.0),
            parameters.get("p2_z", 1.0),
        )
        
        dx = p1[0] - p2[0]
        dy = p1[1] - p2[1]
        dz = p1[2] - p2[2]
        distance = math.sqrt(dx*dx + dy*dy + dz*dz)
        
        message = f"Distance: {distance:.4f} units"
        output = f"{distance:.4f}"
        
        return {
            "success": True,
            "message": message,
            "execution_time": 0.1,
            "memory_used_mb": 0.1,
            "output": output,
        }
    
    else:
        return {
            "success": False,
            "message": f"Unknown operation '{operation}'",
            "execution_time": 0.0,
            "memory_used_mb": 0.0,
            "output": "",
        }


def sandbox_create_config(
    max_execution_time: float = 30.0,
    max_memory_mb: int = 1024,
    allowed_operations: list | None = None,
    disallowed_operations: list | None = None,
    max_result_size_mb: int = 100,
) -> SandboxConfig:
    """Create a sandbox configuration."""
    return SandboxConfig(
        max_execution_time=max_execution_time,
        max_memory_mb=max_memory_mb,
        allowed_operations=allowed_operations,
        disallowed_operations=disallowed_operations,
        max_result_size_mb=max_result_size_mb,
    )


def sandbox_status(config: SandboxConfig) -> dict:
    """Get sandbox security status."""
    return {
        "max_execution_time": config.max_execution_time,
        "max_memory_mb": config.max_memory_mb,
        "allowed_operations_count": len(config.allowed_operations),
        "disallowed_operations_count": len(config.disallowed_operations),
    }


def sandbox_test() -> str:
    """Test the sandbox module."""
    return "Sandbox module is operational (Python fallback)"


# ============================================================
# Module exports
# ============================================================

__all__ = [
    "SandboxConfig",
    "SandboxResult",
    "sandbox_create_config",
    "sandbox_execute",
    "sandbox_status",
    "sandbox_test",
]